### ISSUE TITLE
Motor Sound Pitch Issues

### ISSUE THREAD

**Issue by jheinem1** [dsandy12/RoboSim_buglog#7]
When rapidly changing motor speed, the simulation will error and break the currently running MATLAB code. I opened the simulation from Powershell and took a screenshot of the error below. It appears to have something to do with the API being used to control the pitch of the motor sound.
![image](https://user-images.githubusercontent.com/70541819/92961431-1239cf80-f424-11ea-9f86-85c3ee95dab8.png)
My operating system is the latest version of Windows 10 (64 bit).

**Comment by dsandy12** [comment]
Duplicate.  This was noted prior to 1.01 and has been fixed.
